apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-machine-deployment
  labels:
    app: fruit-machine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit-machine
  template:
    metadata:
      labels:
        app: fruit-machine
    spec:
      containers:
      - name: fruit-machine
        image: gcr.io/fruitmachine/github.com/p4rk/fruitmachine:0.0.2


